language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - apt-get install llvm-3.9
  - export LLVM_CONFIG=$(which llvm-config-3.9)
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest